### ISSUE TITLE
[FR] Optional interrupt output that can be used to increment a counter

### ISSUE THREAD

**Issue by DrJKL** [Pos13/comfyui-cyclist#1]
Something that would save a user from having to remember to rename the project.

I think it could be done with the existing logic nodes already, haven't started experimenting yet, but it feels like the interrupt would be a reasonable place to hook that in, to me at least.

**Comment by Pos13** [comment]
@DrJKL That's a great idea! 👍But it'll be tricky to implement. You can't route "**Interrupt**"'s output back to "**Read something**" node, because ComfyUI frontend forbids link loops.
I think the best option would be having some kind of "Loop Manager" node, where you can see exactly what is stored in memory right now. I'll add "_increment on interrupt_" boolean option and "_loop_id_" output.
Going to code it soon.

**Comment by Pos13** [comment]
Done! "**Loop Manager**" node is delivered. I'm about to test it, update example workflows and description soon.
